name: Python CI

# Step 1: When should this run?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Step 2: What should it do?
jobs:
  build:
    runs-on: ubuntu-latest  # Tells GitHub to give a fresh Linux machine

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # "downloads" repo onto the Linux machine

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8  # A tool to check for code errors
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics


  deploy:
    needs: build  # This ensures we only deploy if the Python check PASSES!
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Push to HF
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |

          # creating a temp folder
          mkdir ../temp
          
          #Copy only the files HF needs into that folder
          cp ui/infer_rating_agent.py ../temp/app.py
          cp requirements.txt ../temp/requirements.txt
          cp -r ui/ ../temp/ui/
          CO README.md ../temp/README.md 

          #Go into that folder and turn it into a tiny, new Git repo
          cd ../temp
          git init -b main
          #Add the remote and push it to Hugging Face Spaces. The token is used for authentication.
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add . 
          
          git commit -m "Deploying lean app version to Hugging Face Spaces"
          git push --force https://rukshan1015:$HF_TOKEN@huggingface.co/spaces/rukshan1015/clinical-safety-auditor main:main
  
  