name: Sync to Hugging Face

# Step 1: When should this run?
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    needs: build  # This ensures we only deploy if the Python check PASSES!
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Push to HF
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
          cp ui/infer_rating_agent.py app.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add app.py
          git commit -m "Deploying latest update"
          git push --force https://rukshan1015:$HF_TOKEN@huggingface.co/spaces/rukshan1015/clinical-safety-auditor main